[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/bmatcuk/doublestar"
  version = "1.1.4"
